/**
 * Generates public/models/CREDITS.md from the model manifest.
 *
 * Generated rather than hand-written so attribution cannot drift away from the assets
 * it describes: adding or swapping a model updates the credits in the same commit.
 *
 * Run: npm run write:credits
 */

import { writeFile } from 'node:fs/promises';
import { existsSync, statSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { ATLAS_BASE, ATTRIBUTION, LICENCE_URL, MODELS } from './models.manifest.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'public', 'models', 'CREDITS.md');

const rows = MODELS.map((model) => {
  const file = path.join(ROOT, 'public', 'models', `${model.id}.glb`);
  const size = existsSync(file) ? `${(statSync(file).size / 1024).toFixed(0)} KB` : '—';
  return `| \`${model.id}.glb\` | ${model.title} | ${model.concepts.join(', ')} | ${size} |`;
});

const body = `# Model credits

All 3D models in this directory are built from the BodyParts3D anatomy atlas.

**Attribution:** ${ATTRIBUTION}

**Source:** ${ATLAS_BASE}

**Licence:** Creative Commons Attribution 4.0 International, as stated at
${LICENCE_URL}

**This licence differs from the code licence.** The source code in this repository is
MIT licensed (see LICENSE in the repository root). That does not apply to these models,
which are governed by the atlas licence above.

**No endorsement.** The Database Center for Life Science does not endorse this project.

## Modifications

Every file here is adapted from the atlas; none is a verbatim copy.
\`scripts/build-organs.mjs\` selects each organ's element meshes, drops speck fragments
under 1 mm across, groups the meshes by the hotspot that names them, converts the atlas's
Z-up coordinates to glTF's Y-up, and writes one named node per group.
\`scripts/optimize-models.mjs\` then welds, simplifies, prunes and Meshopt-compresses
each organ, keeping the named groups separate.

Raw sources are not committed. Reproduce the contents of this directory with:

\`\`\`bash
npm run fetch:models && npm run build:organs && npm run optimize:models
\`\`\`

## Files

| File | Organ | FMA concept(s) | Optimised size |
| --- | --- | --- | --- |
${rows.join('\n')}

## Accuracy

The atlas models one reference adult. Shapes are simplified by the optimisation above
and vary between real people; treat them as illustrative. The figures in the
application are transcribed from the sources cited beside them.

<!-- Generated by scripts/write-credits.mjs — edit that, not this file. -->
`;

await writeFile(OUT, body, 'utf8');
console.log(`write-credits: wrote ${path.relative(ROOT, OUT)} (${MODELS.length} models)`);
